Issue# 988: Test Coverage for AtomicCountProcedure
eclipse/eclipse-collections pull request #1012
Opened 2020-10-04 21:38 UTC by hongliu2020

@donraab 
Hi, Don
Can you please review the pull request for issue #988? 
A few questions: 
(1) I don't see mockito in test project as dependency. I'm asking because my first impression is to mock a Predicate to test AtomicCountPrecedure, and I don't see mockito used anywhere in eclipse collection test cases. 
(2) Is it a standard to add comments for unit test cases in the project?

Thanks!
Hong

2020-10-04 21:48 UTC, donraab requested changes
HI @hongliu2020, thank you for the contribution! I've added a few comments inline. On your question of Mockito, we have never had a need to mock anything like `Predicate`. It is easy enough to create inner classes or anonymous implementations to validate that the different function types are visited. In terms of commenting in tests, it is completely up to the developer, but generally we like the tests to be self-explanatory. Other than that, this test looks good to me.

2020-10-04 21:48 UTC, donraab commented on unit-tests/src/test/java/org/eclipse/collections/impl/block/procedure/AtomicCountProcedureTest.java
> +        AtomicCountProcedure<String> atomicCountProcedure = new AtomicCountProcedure<>((Predicate<String>) each ->
Hi @hongliu2020, I would expect the cast to predicate here to be unnecessary. Can you try removing it?

2020-10-04 21:48 UTC, donraab commented on unit-tests/src/test/java/org/eclipse/collections/impl/block/procedure/AtomicCountProcedureTest.java
> +        AtomicCountProcedure<String> atomicCountProcedure = new AtomicCountProcedure<>((Predicate<String>) each ->
Same comment as above on the cast.

2020-10-04 21:48 UTC, donraab commented on unit-tests/src/test/java/org/eclipse/collections/impl/block/procedure/AtomicCountProcedureTest.java
> +    private static final int ZERO = STRING_LENGTH - 5;
I would recommend inlining 0 as it will be more self explanatory.

2020-10-06 04:19 UTC, donraab commented
Hi @hongliu2020, thank you for the changes. These look good.

There is one test I think we are missing for `AtomicCountProcedure` which is a test for parallelism. If you create a List with 50,000 `Integers` and filter out all the evens using an `Executor` with 5 threads in a fixed thread pool, you should consistently get an answer of 25,000 from the count. This same code should fail using a `CountProcedure` which does not use an `AtomicInteger`.

2020-10-06 13:34 UTC, hongliu2020 commented
Hi, @donraab,  it is very good point, I will add test for parallelism accordingly.

2020-10-17 15:38 UTC, hongliu2020 commented
@donraab , Can you please review again? 
Thanks! 
Hong

2020-10-17 22:14 UTC, donraab requested changes
Hi @hongliu2020, thank you for the contribution! The additions in the test look good, but it looks like some file deletions were included unintentionally in the commit. Please address and I will approve and merge. Thanks!

2020-10-18 02:30 UTC, hongliu2020 commented
@donraab , I added .idea files back. Those 4 files were deleted automatically and updated with different versions by Intellij on my local. I'm wondering if the files under .idea/libraries should be specified in .gitignore? Thanks! Hong

2020-10-18 03:04 UTC, donraab approved these changes
LGTM. Thanks for the contribution @hongliu2020!

Please rebase your PR and I will merge.

2020-10-18 17:00 UTC, merged