Add test cases for BagAddOccurancesProcedure
eclipse/eclipse-collections pull request #1015
Opened 2020-10-16 21:28 UTC by jonathansamuel-bnym

Closes #989 

The BagAddOccurancesProcedure was missing test cases. I added a test case to cover adding occurrences to an existing bag. I also added a test case to cover the factory method.

2020-10-17 00:13 UTC, donraab requested changes
Hi @jonathansamuel-bnym, thank you very much for the contribution. The checkstyle build is failing, and it looks like you need to sign off your commit as the Eclipse Foundation check is failing as well. Please address these issues and I can approve and merge once the builds pass.  Please correct the spelling error in the PR title and commit message as well. It should be Occurrences, not Occurances in BagAddOccurrencesProcedure. Thanks!

2020-10-17 00:13 UTC, donraab commented on unit-tests/src/test/java/org/eclipse/collections/impl/block/procedure/BagAddOccurrencesProcedureTest.java
> +import org.eclipse.collections.api.list.primitive.ImmutableBooleanList;
There are several unused imports that are failing the checkstyle build. Please review the build failure and optimize the imports in the class.

2020-10-19 14:30 UTC, jonathansamuel-bnym commented
Removed unused imports, and added sign off to commit. Let's try this again.

2020-10-19 18:18 UTC, donraab commented
Thanks @jonathansamuel-bnym. One last change request to address.

> Please correct the spelling error in the PR title and commit message as well. It should be Occurrences, not Occurances in BagAddOccurrencesProcedure.

2020-10-19 18:27 UTC, nikhilnanivadekar commented
If it is closing an issue please have that as well in the commit message

2020-10-20 03:35 UTC, donraab approved these changes
LGTM. Thanks for the contribution @jonathansamuel-bnym !

2020-10-20 03:35 UTC, merged