Use enhanced for-loop syntax wherever as possible
eclipse/eclipse-collections pull request #1051
Opened 2021-01-05 17:40 UTC by amCap1712

2021-01-05 17:46 UTC, mohrezaei requested changes

2021-01-05 17:46 UTC, mohrezaei commented on eclipse-collections/src/main/java/org/eclipse/collections/impl/block/procedure/CaseProcedure.java
> +        for (Pair<Predicate<? super T>, Procedure<? super T>> pair : this.predicateProcedures)
this is not the same: so-called-enhanced for loop creates garbage.

2021-01-05 17:46 UTC, mohrezaei commented on eclipse-collections/src/main/java/org/eclipse/collections/impl/block/procedure/ChainedProcedure.java
> +        for (Procedure<? super T> procedure : this.procedures)
this is not the same: so-called-enhanced for loop creates garbage.

2021-01-05 17:46 UTC, mohrezaei commented on eclipse-collections/src/main/java/org/eclipse/collections/impl/collection/mutable/AbstractMutableCollection.java
> +            for (T t : list)
this is not the same: so-called-enhanced for loop creates garbage.

2021-01-05 17:46 UTC, mohrezaei commented on eclipse-collections/src/main/java/org/eclipse/collections/impl/list/mutable/CompositeFastList.java
> +        for (List<E> list : this.lists)
this is not the same: so-called-enhanced for loop creates garbage.

2021-01-05 17:46 UTC, mohrezaei commented on eclipse-collections/src/main/java/org/eclipse/collections/impl/list/mutable/CompositeFastList.java
> +        for (MutableList<E> list : this.lists)
this is not the same: so-called-enhanced for loop creates garbage. (many more... any time there is a `list.get()`)

2021-01-12 03:49 UTC, donraab requested changes
Thank you for the contribution @amCap1712! As @mohrezaei has commented a few times, anywhere you replace indexed access against a List with the for-each loop syntax from Java 5, you will introduce an undesirable generation of an Iterator. We have optimized against this pattern for performance reasons since the early days of the library. Anywhere you are replacing existing Iterator creations with the simplified for-loop is a good change and is most welcome. Also, you can safely use the for-loop when iterating over arrays as long as the entire array is iterated over.

2021-01-12 09:02 UTC, amCap1712 commented
Thanks for the reviews @donraab and @mohrezaei. I have updated the PR in accordance with it.

2021-01-12 19:04 UTC, mohrezaei approved these changes

2021-02-26 00:45 UTC, donraab approved these changes
LGTM. Thanks for the contribution @amCap1712 !

2021-02-26 00:49 UTC, prathasirisha commented
Hi @amCap1712, thank you for the contribution. Apologies for the delayed response.  Can you please rebase your PR, so one of us can merge this in.

2021-03-08 10:13 UTC, amCap1712 commented
Hi! I had updated the PR. But one check fails, don't know if its connected to changes in this PR.

2021-03-10 18:22 UTC, prathasirisha commented
Hi @amCap1712, it may not be related to your PR. Of late we are experiencing occasional build timeouts on TeamCity. Unfortunately, we can't tell if the build would be successful or not for us to proceed with the merge. 
Can you please rebase and push once more (I merged a different PR few minutes back so your branch is 2 commits behind)?  Thank you for being patient!

2021-03-30 05:31 UTC, donraab commented
Hi @amCap1712 If you can rebase again, @prathasirisha or I will merge your PR. The builds are passing for your PR, so if anything fails after you rebase, we'll just restart any failed builds and merge after they pass. Thanks!

2021-03-31 20:11 UTC, amCap1712 commented
Apologies for the delay. I have updated the PR.

2021-03-31 23:18 UTC, merged