Fix return types of aggregateBy().
eclipse/eclipse-collections pull request #1061
Opened 2021-02-10 16:12 UTC by motlin

2021-02-23 16:38 UTC, donraab approved these changes
LGTM

2021-02-25 00:40 UTC, prathasirisha requested changes
Hi @motlin, a minor comment - copyright information (year) needs to be updated in a couple of places. The rest looks good and we can go ahead and merge this PR when you have updated it. Thank you!

2021-03-16 14:07 UTC, motlin commented
@prathasirisha fixed

2021-03-16 23:13 UTC, prathasirisha approved these changes

2021-03-16 23:15 UTC, merged