#1109 Improve pit test coverage
eclipse/eclipse-collections pull request #1110
Opened 2021-06-17 21:25 UTC by goldbal330

Signed-off-by: Alexander Goldberg <alexander.goldberg@bnymellon.com>

2021-06-22 14:14 UTC, goldbal330 commented
PR submitted

2021-06-22 20:51 UTC, donraab requested changes
In progress reviewing. Please address consistency issues on the copyright notices. Thanks!

2021-06-22 20:51 UTC, donraab commented on unit-tests/src/test/java/org/eclipse/collections/impl/block/procedure/AdaptObjectIntProcedureToProcedureTest.java
> + * Copyright (c) 2021 Goldman Sachs.
Add "and others" after GS.

2021-06-22 20:51 UTC, donraab commented on unit-tests/src/test/java/org/eclipse/collections/impl/block/procedure/CaseProcedureTest.java
> +        Verify.assertSame(procedure, procedure.setDefault(result::add));
Add "and others" in the copyright.

2021-06-22 20:51 UTC, donraab commented on unit-tests/src/test/java/org/eclipse/collections/impl/block/procedure/ChainedProcedureTest.java
> +
Same comment on copyright.

2021-06-22 20:51 UTC, donraab commented on unit-tests/src/test/java/org/eclipse/collections/impl/block/procedure/IfProcedureTest.java
> +import org.eclipse.collections.impl.utility.StringIterate;
Same comment on copyright.

2021-06-23 00:25 UTC, prathasirisha commented on unit-tests/src/test/java/org/eclipse/collections/impl/block/procedure/CollectionAddProcedureTest.java
> +public class CollectionAddProcedureTest
Hi Alex, noticed there were few other methods in this class that are not being covered in the test cases. Can you add tests for those as well?

2021-06-23 14:28 UTC, closed without merging