#1109 Improve Pit Coverage
eclipse/eclipse-collections pull request #1113
Opened 2021-06-23 16:37 UTC by goldbal330

Signed-off-by: Alexander Goldberg <alexander.goldberg@bnymellon.com>

2021-08-13 02:26 UTC, prathasirisha requested changes
Added one minor comment on copyright update.

2021-08-13 02:26 UTC, prathasirisha commented on unit-tests/src/test/java/org/eclipse/collections/impl/block/procedure/MaxProcedureTest.java
> + * Copyright (c) 2021 Goldman Sachs and others.
This needs to be updated.

2021-08-14 19:40 UTC, prathasirisha commented
@goldbal330 Thank you for your contribution. 😃 

One last comment, could you please update the commit message to reflect new tests are being added. This will help us a lot when we are preparing releasing notes. Commit message guidelines available [here](https://github.com/eclipse/eclipse-collections/blob/master/CONTRIBUTING.md#commit-messages).

2021-08-14 21:47 UTC, nikhilnanivadekar commented
My only comment on this would be that we have another PR covering same tests by a new contributor. In the spirit of promoting new contributions can we see if we can selectively merge those PRs first and then this one. Thoughts?

2021-08-18 01:18 UTC, prathasirisha approved these changes

2021-08-18 01:29 UTC, merged