Add JDK 17 to standard builds and update EA builds to JDK 18.
eclipse/eclipse-collections pull request #1142
Opened 2021-09-21 02:49 UTC by donraab

Signed-off-by: Donald Raab <Donald.Raab@bnymellon.com>

2021-09-22 15:33 UTC, nikhilnanivadekar commented
We should move checkstyle to 17.

2021-09-22 15:35 UTC, nikhilnanivadekar commented
This one should only run on 8 and 11 : https://github.com/eclipse/eclipse-collections/blob/master/.github/workflows/unit.yml

2021-09-22 15:36 UTC, nikhilnanivadekar requested changes

2021-09-22 15:36 UTC, nikhilnanivadekar commented on .github/workflows/unit-no-p2.yml
> +        java-version: [15, 16, 17]
We should probably only have it as 17

2021-09-23 03:25 UTC, donraab commented
> We should move checkstyle to 17.

I tried and it failed. I rolled back to 11.

2021-09-23 03:25 UTC, donraab commented
> This one should only run on 8 and 11 : https://github.com/eclipse/eclipse-collections/blob/master/.github/workflows/unit.yml

Done.

2021-09-23 03:25 UTC, donraab commented on .github/workflows/unit-no-p2.yml
> +        java-version: [15, 16, 17]
Done

2021-09-23 03:25 UTC, donraab commented
Ready to merge.

2021-09-27 03:20 UTC, nikhilnanivadekar approved these changes

2021-09-27 03:20 UTC, merged