implement subList() on primitive immutable lists
eclipse/eclipse-collections pull request #1160
Opened 2021-11-23 15:48 UTC by sneznaj

implement subList() on primitive immutable lists

part of #1053

AbstractImmutableList defines  subList() as returning an object of an inner class
but here it is implemented as returning an object of the class itself

2021-11-23 19:06 UTC, mohrezaei requested changes

2021-11-23 19:06 UTC, mohrezaei commented on eclipse-collections/src/main/java/org/eclipse/collections/impl/list/immutable/primitive/ImmutableBooleanArrayList.java
> +        return new ImmutableBooleanArrayList(this.BitSet.get(fromIndex, toIndex), toIndex - fromIndex)
copying the bitset is too expensive. Use a subclass instead.

2021-11-23 19:06 UTC, mohrezaei commented on eclipse-collections/src/main/java/org/eclipse/collections/impl/list/primitive/LongInterval.java
> +        return new LongInterval(fromIndex, toIndex, this.step);
this looks wrong. The fromIndex/toIndex of the list is not the same as the from/to of the interval.

2021-11-23 19:08 UTC, mohrezaei commented
Sorry, when I asked for not using a subclass, I only meant `LongInterval`.
Two more things:

- Please don't create new PRs for the same work. Just push more code to your branch. You're using master, which is a bit unusual, but it should work the same.
- You must add tests for all the new code.

2022-04-25 20:18 UTC, donraab commented
Closing this as two PRs with the same name could be a single PR.

2022-04-25 20:18 UTC, closed without merging