#1109: Improve Pit Coverage
eclipse/eclipse-collections pull request #1195
Opened 2022-02-16 21:56 UTC by goldbal330

Signed-off-by: Alexander Goldberg <alexander.goldberg@bnymellon.com>

2022-03-02 00:16 UTC, donraab requested changes
Thanks for the contribution @goldbal330. A few changes requested.

2022-03-02 22:05 UTC, goldbal330 commented on eclipse-collections-code-generator/src/main/resources/test/utility/lazyPrimitiveIterateTest.stg
> +        Assert.assertEquals(this.iterable, <name>Lists.mutable.ofAll(<type>Iterable));
Fixed!

2022-03-02 22:05 UTC, goldbal330 commented on eclipse-collections-code-generator/src/main/resources/test/utility/singletonPrimitiveIteratorTest.stg
> +import "copyright.stg"
Replaced.

2022-03-02 22:06 UTC, goldbal330 commented on unit-tests/src/test/java/org/eclipse/collections/impl/block/function/primitive/BooleanCaseFunctionTest.java
> + * Copyright (c) 2022 Goldman Sachs and others.
Done!

2022-03-02 22:06 UTC, goldbal330 commented on unit-tests/src/test/java/org/eclipse/collections/impl/utility/primitive/LazyBooleanIterateTest.java
> +        Assert.assertEquals(this.iterable, BooleanLists.mutable.ofAll(booleanIterable));
done!

2022-03-03 03:35 UTC, donraab approved these changes
LGTM. Thanks for the contribution @goldbal330 !

2022-03-03 03:35 UTC, merged