Add Map implementation and tests for containsAny/containsNone without…
eclipse/eclipse-collections pull request #1341
Opened 2022-05-01 01:22 UTC by donraab

… iterator

Signed-off-by: Donald Raab <Donald.Raab@bnymellon.com>

2022-05-01 03:53 UTC, mohrezaei requested changes
`this.containsValue` is `O(n)`, which makes these methods `O(m*n)` all the time. 

If the incoming collection has a fast `contains` (because it's tiny or `O(1)`), the order should be reversed.

2022-05-02 02:21 UTC, donraab commented
> `this.containsValue` is `O(n)`, which makes these methods `O(m*n)` all the time.
> 
> If the incoming collection has a fast `contains` (because it's tiny or `O(1)`), the order should be reversed.

Yes, agreed. The `containsAll` implementation is currently suffering from this as well. I wanted to get the patterns working first without iterators as `containsAll` is. Then I figured I would try and tackle optimizing all three patterns on `UnifiedMap`.

2022-05-02 03:35 UTC, donraab commented
@mohrezaei I discovered there are some open TODOs to optimize `UnifiedMapWithHashingStrategy` for `anySatisfy`/`allSatisfy`/`noneSatisfy` to not use iterator. I have reverted my changes as `UnifiedMap` was already optimal, and I've overridden the failing tests for `UnifiedMapWithHashingStrategy`.

The optimizations of `anySatisfy`/`allSatisfy`/`noneSatisfy` can be done in a separate PR.

2022-05-02 03:47 UTC, mohrezaei approved these changes

2022-05-02 04:11 UTC, merged