updated typo
eclipse/eclipse-collections pull request #1389
Opened 2022-09-07 05:29 UTC by Akash3121

updated typo in Primitive Lists Example:38 from creCreate to Create.

2022-09-07 07:52 UTC, Akash3121 commented
Hello @nikhilnanivadekar, Thanks for the Inspections.
I'm new to this, I need help regarding eclipsefdn/eca (The author(s) of the pull request is not covered by necessary legal agreements) - errored.
https://accounts.eclipse.org/legal/eca/validation/118828
I've signed the ECA and Revalidated but still it's same.
Thanks and Regards,
Akash

2022-09-08 09:33 UTC, Akash3121 commented
Hello @donraab, Thank you for your suggestion to go for a PR to correct a typo, https://github.com/eclipse/eclipse-collections/issues/1383#issuecomment-1238915208.
I'm new to this, I need help regarding **eclipsefdn/eca** (The author(s) of the pull request is **not** covered by necessary legal agreements) - errored.
https://accounts.eclipse.org/legal/eca/validation/118828
I've signed the ECA and Revalidated but it's still same. Is there anything that I can do to solve that error.
Thanks and Regards,
Akash

2022-09-08 16:22 UTC, donraab requested changes
Hi @Akash3121, thank you for the contribution! Looks like the ECA validation is passing now. One minor change requested. Make sure to squash any commits and rebase and then I can approve once everything looks good.

2022-09-08 16:22 UTC, donraab commented on docs/2-Collection_Containers.adoc
> +.our ways to Create an *IntArrayList*, use one of the following:
should be a lowercase c

2022-09-09 04:40 UTC, Akash3121 commented on docs/2-Collection_Containers.adoc
> +.our ways to Create an *IntArrayList*, use one of the following:
Yes Sir, will do that.

2022-09-09 04:43 UTC, Akash3121 commented
Hi @donraab, Thank you for guiding me in my initial contribution.
"C" changed to small case and squashed commits.
Thanks & Regards,
Akash.

2022-09-09 23:22 UTC, donraab approved these changes
LGTM! Thanks for the contribution!

2022-09-09 23:22 UTC, merged