2-Collection_Containers.adoc file updated for IntInterval Document
eclipse/eclipse-collections pull request #1399
Opened 2022-09-26 16:37 UTC by sandip1805

#1384 
Added examples for IntInterval class with different set of examples.

2022-09-26 16:38 UTC, sandip1805 commented
@donraab , can you please have review of this PR?

2022-09-27 18:14 UTC, donraab requested changes
Thanks for the contribution @sandip1805! Some changes requested inline.

2022-09-28 16:34 UTC, sandip1805 commented on docs/2-Collection_Containers.adoc
> +ImmutableIntList intInterval = IntInterval.fromTo(1, 5);
Thank you @donraab for suggestion. I like your idea to use Assertions instead of adding in comment. I will work on this implement suggested changes.

2022-10-03 02:37 UTC, donraab approved these changes
LGTM. Thank you for the contribution @sandip1805 ! Please squash your commits and I will merge.

2022-10-03 16:33 UTC, sandip1805 commented
> LGTM. Thank you for the contribution @sandip1805 ! Please squash your commits and I will merge.

Hi @donraab , Squashed commits.

2022-10-05 05:10 UTC, donraab approved these changes
LGTM. Thanks for the contribution @sandip1805 !

2022-10-05 05:11 UTC, merged

2022-10-05 05:27 UTC, sandip1805 commented
Hi @donraab , Thanks for merging this PR,  I would like to contribute on some code level issues, do you have any issue where I can contribute?