Implemented boxing wrappers for primitive lists. #1408.
eclipse/eclipse-collections pull request #1448
Opened 2023-03-24 15:53 UTC by goldbal330

2023-03-25 01:34 UTC, donraab commented
@goldbal330 I think you meant this to be "Implemented boxing wrappers for primitive sets."

2023-03-27 16:04 UTC, donraab requested changes
Thanks for the contribution @goldbal330 ! A few changes requested inline.

2023-03-27 17:53 UTC, goldbal330 commented on eclipse-collections-code-generator/src/main/resources/impl/set/mutable/boxedPrimitiveSet.stg
> + * @since 12.0.1
Fixed

2023-03-27 17:53 UTC, goldbal330 commented on .idea/jarRepositories.xml
Removed.

2023-03-27 19:24 UTC, donraab approved these changes
LGTM. Thanks for the contribution @goldbal330 !

2023-03-29 04:12 UTC, merged