Add toStack to Ordered primitive Iterable
eclipse/eclipse-collections pull request #1528
Opened 2023-11-23 11:50 UTC by DineshPurushothamacharya

Signed-off-by: Dinesh Purushothamacharya <Dinesh.Purushothamacharya@cerner.com>

Add toStack to Ordered primitive Iterable

Signed-off-by: Dinesh Purushothamacharya <Dinesh.Purushothamacharya@cerner.com>

rebase with master

Signed-off-by: Dinesh Purushothamacharya <p.dinesh87@gmail.com>

rebase with master

Signed-off-by: Dinesh Purushothamacharya <p.dinesh87@gmail.com>

Add toStack to Ordered Primitive Iterable

Signed-off-by: Dinesh Purushothamacharya <p.dinesh87@gmail.com>

Fix checkstyle Issue

Signed-off-by: Dinesh Purushothamacharya <p.dinesh87@gmail.com>

Add unit tests to support toStack implmentation

Signed-off-by: Dinesh Purushothamacharya <p.dinesh87@gmail.com>

rebase

rebase

rebase

rebase with master

Signed-off-by: Dinesh Purushothamacharya <p.dinesh87@gmail.com>

Add toStack to Ordered Primitive Iterable

Signed-off-by: Dinesh Purushothamacharya <p.dinesh87@gmail.com>

Revert "rebase"

This reverts commit cb766b17e8c346e9dcc0c9ba9317722c299a5117.

fix rebase issues

restore xml files

add .gitignore file

Signed-off-by: Dinesh Purushothamacharya <p.dinesh87@gmail.com>

fix checkstyle issues

Signed-off-by: Dinesh Purushothamacharya <p.dinesh87@gmail.com>

Fix checkstyle issue

Signed-off-by: Dinesh Purushothamacharya <p.dinesh87@gmail.com>

fix checkstyle issues

Signed-off-by: Dinesh Purushothamacharya <p.dinesh87@gmail.com>

Fix assertions

2023-11-28 09:52 UTC, DineshPurushothamacharya commented
Hello @donraab could you please review and merge this pull request.

2023-11-28 18:53 UTC, donraab commented
> Hello @donraab could you please review and merge this pull request.

Hi @DineshPurushothamacharya, yes, before I give a quick review again, can you update the commit message and PR message... they both have a log of a lot of activity and other unimportant stuff.  Thanks!

2023-11-29 07:03 UTC, donraab requested changes
Hi @DineshPurushothamacharya, I have one minor change requested inline. Also, if you can clean up the commit and PR comments as they have a log of all the changes with extra unnecessary info. Thanks for being so patient!

2023-12-02 19:15 UTC, donraab commented
HI @DineshPurushothamacharya, I am ready to merge once you make these two small changes. I am not going to merge anything else until this PR is merged. Thanks!

2023-12-03 07:17 UTC, DineshPurushothamacharya commented on eclipse-collections-code-generator/src/main/resources/test/stack/immutable/immutablePrimitiveArrayStackTest.stg
> +        Assert.assertEquals(stack, <name>ArrayStack.newStackWith(<["1", "2", "3"]:(literal.(type))(); separator=", ">).toStack());
Done.

2023-12-03 07:18 UTC, DineshPurushothamacharya commented
> HI @DineshPurushothamacharya, I am ready to merge once you make these two small changes. I am not going to merge anything else until this PR is merged, because you've been patient and waited long enough. Thanks!

Hi @donraab I have made the changes as you have requested. Please check.

2023-12-03 07:26 UTC, donraab approved these changes
LGTM! Thank you for the contribution and your patience @DineshPurushothamacharya! I will merge once the builds pass.

2023-12-03 08:17 UTC, merged