Implement RichIterable.reduceBy(). Fixes #134
eclipse/eclipse-collections pull request #1540
Opened 2024-01-08 13:09 UTC by motlin

2024-02-14 00:00 UTC, donraab requested changes
@motlin This looks like a nice addition. I would recommend adding at since 12.0 tags in all of the interfaces. I also think there needs to be special handling for MultiReader classes, similar to the synchronized types.

2024-02-14 23:16 UTC, motlin commented
> @motlin This looks like a nice addition. I would recommend adding at since 12.0 tags in all of the interfaces. I also think there needs to be special handling for MultiReader classes, similar to the synchronized types.

I'm about to push a new change that updates since from `?` to `12.0` and overrides these methods in `AbstractMultiReaderMutableCollection`. However, I picked the places to place overrides by following the places where we have overridden the methods `aggregateBy`, `countBy`, `groupBy` etc. None of these methods are overridden in the MultiReader collections. I don't think they need to be for correctness, because they're all implemented by delegating to forEach() which does the right thing. It might be nice to override them for other reasons.

2024-02-16 15:15 UTC, motlin commented
@donraab I see your 👍  but you still have the request for changes so I want to make sure it's all good before I click Merge.

2024-02-16 15:50 UTC, donraab requested changes
One small fix and then LGTM

2024-02-17 00:06 UTC, donraab commented on eclipse-collections-api/src/main/java/org/eclipse/collections/api/RichIterable.java
> +     * @since ?
Should be since 12.0 not since ?

2024-02-17 05:42 UTC, donraab approved these changes
LGTM

2024-02-17 05:55 UTC, merged