Documentation on serializing EC with jackson
eclipse/eclipse-collections pull request #997
Opened 2020-09-09 21:18 UTC by yawkat

This is an old draft blog article of mine. The 'Eclipse Collections' section should probably be removed, explaining that is the job of other docs. Feedback appreciated!

2020-09-09 21:20 UTC, yawkat commented
Will do the ECA tomorrow.

2020-09-09 21:22 UTC, donraab commented
Thanks @yawkat! You'll need to sign-off and amend your commit after the ECA. I'll take a look and provide feedback. This is very much appreciated!

2020-09-09 21:31 UTC, donraab requested changes
Hi @yawkat, thank you very much for the great contribution! I've requested a few changes inline. I think the Eclipse Collections community will really appreciate learning about this.

2020-09-09 21:31 UTC, donraab commented on docs/jackson.md
> +[Eclipse Collections](https://www.eclipse.org/collections/) is a framework that aims to complement the collection library we all know in `java.util`. It offers immutable collections, primitive collec
Just drop the first paragraph.

2020-09-09 21:31 UTC, donraab commented on docs/jackson.md
> +# Serializing Eclipse Collections with Jackson
Include a Copyright Header similar the [ref guide.](https://raw.githubusercontent.com/eclipse/eclipse-collections/master/docs/guide.md)

2020-09-09 21:31 UTC, donraab commented on docs/jackson.md
> +    <version>9.2.0</version>
Update version to 10.4.0

2020-09-09 21:31 UTC, donraab commented on docs/jackson.md
> +compile 'org.eclipse.collections:eclipse-collections:9.2.0'
Update version to 10.4.0

2020-09-09 21:31 UTC, donraab commented on docs/jackson.md
> +9.2.0 is the current Eclipse Collections version at time of writing. Check out [the maven repo](https://search.maven.org/search?q=g:org.eclipse.collections%20AND%20a:eclipse-collections&core=gav) for
I think you can just remove this paragraph.

2020-09-09 21:31 UTC, donraab commented on docs/jackson.md
> +  <version>2.9.8</version>
Update to current version.

2020-09-09 21:31 UTC, donraab commented on docs/jackson.md
> +  <version>2.9.8</version>
Update to current version.

2020-09-09 21:31 UTC, donraab commented on docs/jackson.md
> +```
Update to current versions.

2020-09-13 01:02 UTC, donraab approved these changes
This looks good to me @yawkat! Please rebase and I will merge.

2020-09-13 16:45 UTC, yawkat commented
that checkstyle failure looks like a random error with maven dependency resolution during build.

2020-09-13 17:11 UTC, nikhilnanivadekar commented
Yes, it’s an annoying problem. I have restarted the build. Even though the change has nothing to do with checkstyle.

2020-09-13 17:54 UTC, merged